### ISSUE TITLE
No module named 'direction'

### ISSUE THREAD

**Issue by HappyDay-design** [tkn-tub/coop#1]
Hello 

Thank you for providing the free tool to create Platoon in Sumo

But when I run the files, I see missing direction module. I tried to install it but it didn't work

For example

Traceback (most recent call last):
  File "d:/Download/coop-master/tests/test_state_transfer/test_leader.py", line 19, in <module>
    from direction import Direction
ModuleNotFoundError: No module named 'direction'

**Comment by heinovski** [comment]
Hi,

what was the command you executed? Did you call `test_leader.py` directly?

In your case, the direction module, which is located in `src`, is seemingly not in your `PYTHONPATH`.

The test can be run like so:
```
env PYTHONPATH=(pwd)/src pytest -v tests/test_state_transfer/test_leader.py
```
or so to run all tests:
```
env PYTHONPATH=$(pwd)/src pytest -v tests/
```

**Comment by HappyDay-design** [comment]
> Hi,
> 
...
> ```

Thank you for your quick reply. I fixed that error. But I run the file test_leader.py and nothing happens.
 I see that file only just declares the class.
![image](https://user-images.githubusercontent.com/82990411/147475829-1e2bf9d5-fc33-456c-98b0-c26141a24ff8.png)

**Comment by heinovski** [comment]
Great!

Your editor is not showing 270 lines of code, since it collapsed them. Directly running the files located in the `tests` directory, however, will not do anything, since these files include code for `pytest`. Therefore, you have to run them with `pytest` as indicated above or in the README.

**Comment by TrinhTuanHung2021** [comment]
Thank you very much.

**Comment by HappyDay-design** [comment]
Thank you very much. I want to change the car following- model of the platoon but it is not possible. vType id="PlatoonCar". Currently, the model is used" CC". I want to switch to "IDM" but I get an error when I run it. Do you know the reason why?
I see that the lanesCount parameter is required in the model.

**Comment by heinovski** [comment]
It seems that this issue has been resolved. I am thus going to close it. Please open a new issue in case you have another problem.
