### ISSUE TITLE
Some questions related to your papers

### ISSUE THREAD

**Issue by HappyDay-design** [tkn-tub/coop#2]
Hello. Thank you for sharing your code

When I run your models and read the papers, I had some questions and I would like to ask you
![image](https://user-images.githubusercontent.com/82990411/170666017-4b57c0c1-a35c-448a-9be6-7a4818403329.png)

![image](https://user-images.githubusercontent.com/82990411/170663799-6af5b33d-597c-4f6f-bf6b-9c25d960a620.png)

1.  you set INTER_VEHICLE_DISTANCE = 5 in parameter.py, but I measured the distance between 2 vehicles in a platoon as 10m. And this is the constant number when moving.

2. Desired Speed of vehicles in your paper is 30.6 m/s. But in the models, the platoon moves at the speed of 27.8m/s

3. And the traffic density. As shown in the papers, you had 3 scenarios in table II with low, medium and high traffic. But I only saw a platoon and 3 other vehicles in your model. 
Thank you very much.

**Comment by heinovski** [comment]
Hi @TrinhTuanHung2021 ,

thanks for checking out our model :-)

The source code we provide here only includes the algorithm itself and some dummy scenario but not the scenario configuration which we used within the paper. Thus, some parameters such as the number of vehicles in a platoon that you mentioned will differ. 

You should be able to reproduce the exact same results by using the information given in the paper. However, the reported behavior of the algorithm should be valid in other configurations as well.

Best,
Julian

**Comment by HappyDay-design** [comment]
> Hi @TrinhTuanHung2021 ,
> 
> thanks for checking out our model :-)
> 
> The source code we provide here only includes the algorithm itself and some dummy scenario but not the scenario configuration which we used within the paper. Thus, some parameters such as the number of vehicles in a platoon that you mentioned will differ.
> 
> You should be able to reproduce the exact same results by using the information given in the paper. However, the reported behavior of the algorithm should be valid in other configurations as well.
> 
> Best, Julian

Thank you very much for your quick reply.
I can create a model with Plexe API. But I can not create many platoons in the model. Could you show me how to create many platoons? Thank you very much

**Comment by heinovski** [comment]
Our code focuses on simulating one platoon only. Thus, you cannot create more than one platoon using our software.

**Comment by HappyDay-design** [comment]
> Our code focuses on simulating one platoon only. Thus, you cannot create more than one platoon using our software.

Thank you very much. I fully understand your papers.

**Comment by heinovski** [comment]
Very good. I am closing this now :-)
